[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.14.3"
itertools = "0.12.0"
num = "0.4.1"
phf = { version = "0.11.2", features = ["macros"] }
rand = "0.8.5"
